lloeki/ex-mode

- package.json
[vim-mode](https://github.com/atom/vim-mode) only provides provideVimMode in version 0.1.0.
Fixes #2, I suppose.
> Fix consumeVim version so we can use it

- lib/command-error.coffee
- lib/command.coffee
- lib/ex-mode.coffee
- lib/ex-state.coffee
- lib/ex.coffee
- lib/find.coffee
- lib/global-ex-state.coffee
- package.json
This comment doesn't really cover everything it should, but I'm a bit short on time and also tired, so test it out if you want to.
Fixes #5, #6 and #25.
This implements command parsing (mainly) following the [ex spec](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/ex.html#tag_20_40_13_03), allowing more powerful commands like :s to be implemented.
Commands in the Ex class are called with the range as the first element, then all text following the command, so they require some rewriting (notably splitting the arguments manually).
There were some design choices to be made, so let's see how you like it.
:'a+10
Moves the cursor to the 10th line after the vim-mode mark `a`.
:'a,?\d?s/\s+/ /g
This would replace all whitespace in the lines between the vim-mode mark `a` and the first …
> Implement parsing following ex spec and :s, fix behaviour of :e

- lib/ex.coffee
`:x` threw an error because the arguments weren't properly passed on.
> Fix `:x` throwing an error

- lib/ex.coffee
In vim, doing `:write path` saves the file under that path, but doesn't change the path of the editor to the path. This PR does the same.
> Fix :write behaviour

- lib/ex.coffee
This fixes #57 and (probably) atom/vim-mode#703.
Apparently, using `TextBuffer`'s history checkpoints caused problems with undoing, both through `vim-mode`'s <kbd>u</kbd> or through core's <kbd>Ctrl-Z</kbd>.
> Use TextEditor.transact

- lib/ex.coffee
This should fix #54.
Currently `:%s/^/\/\//` will insert `\/\/` before each line, where it should insert `//`.
> Replace `\#{delimiter}` with `#{delimiter}` in :s

- lib/ex.coffee
- lib/vim-option.coffee
This PR closes #68 and implements part of #8.
Implemented options are number(nu)/nonumber(nonu) and list/nolist.
I'm quite new to js/coffee-script and at the moment I'm unsure if I did it right with creating option class, though I mostly followed example of Ex.
Also the naming of the option class itself, `VimOption`, could be a subject of discussion.
> Add support for :set [option]

- styles/ex-mode.less
Display ':' at start of the command input line
To match how Vim behaves when entering commands
> Display ':' at start of the command input line

- styles/ex-mode.less
Changed the style of .command-mode-input so that it looks like
.normal-mode-input from vim-mode.
This makes ex-mode more consistent with vim-mode
> Make cmd-line in ex-mode look like in vim-mode

- lib/ex.coffee
- spec/ex-commands-spec.coffee
> Instead of the '/' which surrounds the pattern and replacement string,
you can use any other single-byte character, but not an alphanumeric
character, '\', '"'' or '|'.
([Vim docs](http://vimdoc.sourceforge.net/htmldoc/change.html#:substitute))
I'm open to suggestions on how to improve the code!
> Don't allow :s delimiters not allowed by vim

- lib/command.coffee
- lib/ex.coffee
- spec/ex-commands-spec.coffee
This reworks the way commands are called. Commands are now called with an object
```coffeescript
{ range, args, vimState, exState, editor }
```
instead of a long list of arguments so they can access more information without bloating the function definition.
This PR also improves `:substitute` so that it replaces escape sequences and allows replacing with an empty string. It also integrates with the vim search history so that you can replace the last search (`:s//abc`) and so that the patterns from `:substitute` also get pushed to the search history.
> Rework command calling, improve :substitute

- lib/ex-normal-mode-input-element.coffee
> backspace over empty `:` now cancels ex-mode

- lib/ex.coffee
Add ability to register alias keys without having to copy the original functions.
Use case example: register `W` as typo fallback for `w`
> Add option to register alias keys in atom init config

- lib/ex.coffee
- spec/ex-commands-spec.coffee
Currently, when running a delete command (e.g., `:1,4d`), the text is deleted but not copied to the clipboard.
This PR causes deleted text to be copied to the clipboard.
> Copy to text to clipboard on delete

- lib/ex.coffee
- spec/ex-commands-spec.coffee
Fixes #146 
- Fixes a bug in the way tabnew forwarded arguments to tabedit.
Calling tabnew with arguments
> Fix tabnew with arguments

- lib/ex.coffee
Fixes #147
- Replaced `Promise.defer()` with a custom `defer()` implementation
> Stop using non-standard Promise.defer()

- lib/autocomplete.coffee
- lib/ex-view-model.coffee
- lib/ex.coffee
- spec/autocomplete-spec.coffee
Fixes #29  .
**Note** I have not tested this on windows, assistance here would be much appreciated
- Adds a listener for the tab key to trigger autocomplete
- Autocompletes commands if only 1 word entered, otherwise paths
> Issue #29 Command and file autocomplete

- lib/ex.coffee
- spec/ex-commands-spec.coffee
Fixes #156.
- Update the editor when a new file is first saved, similar to `:saveas`
Fixes #156
> Update editor when saving a new file with `:w` or `:saveas`

- lib/vim-option.coffee
- spec/ex-commands-spec.coffee
- Make the existing splitbelow and splitright package options available via `:set`
> Add splitbelow and splitright options to `:set`

- lib/command.coffee
- lib/ex-state.coffee
- lib/ex-view-model.coffee
- spec/ex-commands-spec.coffee
- spec/ex-input-spec.coffee
- When opening the Ex line with selections open, start off with `'<,'>` in the input field
- When the range for the command is `'<,'>`, run the command on every selection (linewise)
- Make the command specs use the `ex-mode:open` command directly instead of `keydown(':')` since that apparently wasn't working
> Basic support for visual marks ('<,'>)

- lib/command.coffee
- spec/ex-commands-spec.coffee
Fixes #70.
- Fix using marks as addresses - no idea where that code came from 😇
- Add specs for addresses by checking how ex behaves when used as a motion (e.g. `:3` or `:'a`)
[](Remove the `[]()` to uncomment the appropriate lines)
[](- New features introduced)
- Bugs fixed
- Neither (I'm just enhancing tests!)
> Fix mark addresses and add specs for addresses

- lib/command.coffee
- lib/find.coffee
- spec/ex-commands-spec.coffee
- Fix search not working without a closing delimiter
[](Remove the `[]()` to uncomment the appropriate lines)
[](- New features introduced)
- Bugs fixed
[](- Neither (I'm just enhancing tests!))
> Fix search not working without a closing delimiter

- lib/autocomplete.coffee
- spec/autocomplete-spec.coffee
- Fix autocompleting a non existent directory (e.g. `tabe /tmp/nothere/`). This was causing an uncaught `ENOENT` error.
[](Remove the `[]()` to uncomment the appropriate lines)
[](- New features introduced)
- Bugs fixed
[](- Neither (I'm just enhancing tests!))
> Autocomplete non existant directory fix

- lib/command.coffee
- spec/ex-commands-spec.coffee
Fixes #169.
Sets both the first and second address to the last line if they are over that line.
Also sets the second address to the first line if it is 0.
- Bugs fixed
> Limit addresses to the last line

- lib/ex.coffee
- spec/ex-commands-spec.coffee
`x` was being matched with `xall` instead of `xit`, so add an alias.
Fixes #167 .
- Make `x` an alias to `xit`
- Bugs fixed
> Fix `:x` closing Atom instead of the current pane

- README.md
- keymaps/ex-mode.cson
- Update the `README` file to mention `vim-mode-plus` as `vim-mode` has been deprecated.
- Update the keymap to match
Tests: I'm not sure a test is necessary for this, would appreciate guidance.
> ex-mode supports vim-mode-plus

- lib/ex-mode.coffee
- lib/ex.coffee
- package.json
Fixes # 128.
- Fix substitute command error in vim-mode-plus
Error caused by `searchHistory` functions not existing, so I add if statements.
I have written tests for: Nothing
Sorry, I'm not sure how to test and how to write this test case...
> [needs tests] Support vim-mode-plus substitute command

- .travis.yml
- lib/command.coffee
- spec/ex-commands-spec.coffee
- spec/ex-input-spec.coffee
- Support marks in vim-mode-plus
- Use vim-mode-plus in specs
- Neither (I'm just enhancing tests!))
> Vim mode plus marks specs

- lib/command.coffee
Fixes https://github.com/lloeki/ex-mode/issues/183.
- using `getLineCount()` if it is available rather than `lines.length`
This seems to fix the issue on my installation of Atom 1.19.0-beta2 (OS X), but I'm gonna double-check the backwards-compatibility works on 1.18 and check back in here.
> use Atom 1.19 buffer API for finding the length of a buffer

- keymaps/ex-mode.cson
- lib/ex-normal-mode-input-element.coffee
Fixes #94
For changelog:
```md
* Added support for canceling ex-mode with Ctrl-C ([#186](https://github.com/lloeki/ex-mode/pull/186))
```
> Support Ctrl-C to cancel ex-mode

- lib/ex.coffee
In Atom 1.19, TextBuffer.save returns a Promise. This commit adds
support to catch this and resolve our internal callbacks when promise
resolves.
Fixes #183 
Needs some testing.
> Support Promise response in trySave

- lib/ex.coffee
- spec/ex-commands-spec.coffee
- Adds the ability to do :sort in ex-mode in the same way as is done in vanilla vim
- If a range is provided, the lines in the range will be sorted
- If no range is provided, all buffered lines will be sorted
- :sort
- :\<range\>sort
> Adds :sort feature

- keymaps/ex-mode.cson
This is merely a suggestion to also default the `ctrl-[` keymap to close ex-mode. This is in addition to the [recent addition of `ctrl-c`](https://github.com/lloeki/ex-mode/pull/186). 
(`vim-mode-plus` also supports `ctrl-[` to exit by default)
This behaviour is very similar to vim's default behaviour:
```
CTRL-[          *c_CTRL-[* *c_<Esc>* *c_Esc*
<Esc>		When typed and 'x' not present in 'cpoptions', quit
Command-line mode without executing.  In macros or when 'x'
present in 'cpoptions', start entered command.
Note: If your <Esc> key is hard to hit on your keyboard, train
yourself to use CTRL-[.
```
Is very similar to the currently supported `ctrl-c`
```
CTRL-C          *c_CTRL-C*
quit command-line without executing
```
> Support Ctrl-[ to close ex-mode

- lib/ex.coffee
Fixes #214 
The previous method used to create a new empty text buffer stopped working with atom 1.19.0. This changes the calls to simply use `atom.workspace.open()`. As [documented](https://atom.io/docs/api/v1.27.1/Workspace#instance-open), it will create a new TextBuffer if called without arguments.
> Fix :enew not working
